# Generated by Django 6.0 on 2026-01-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, unique=True, verbose_name='Ед. изм. (EN)')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Ед. изм. (RU)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cocktail',
            options={'ordering': ('-id',)},
        ),
    ]
